version: '3'
services:
  database:
    image: artifactory.enzo.net:8000/tech_view:test
    container_name: database
    expose:
      - "5432"
    ports:
      - "5432:5432"

  dashcharts:
    image: artifactory.enzo.net:8000/analytics:2018_08_06local
#analytics:2018_07_21local
    container_name: dashcharts
    links:
      - database
    depends_on:
      - database
    ports:
     - "5000:5000"

  rcharts:
    image: artifactory.enzo.net:8000/r_analytics:2018_08_06
    container_name: rcharts
    links:
      - database
    depends_on:
      - database
    ports:
     - "3838:3838"
  
  nginx:
    image: artifactory.enzo.net:8000/analytic_nginx:2018_04_23
    container_name: nginx
    links:
     - rcharts
     - dashcharts
    depends_on:
     - rcharts
     - dashcharts
    expose:
     - "80"
    ports:
     - "80:8080"
