version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    depends_on:
     - elasticsearch
    environment:
     SERVER_NAME: "localhost"
     ELASTICSEARCH_URL: "http://elasticsearch:9200"
volumes:
  esdata:
    driver: local

